# Generated by Django 2.0.9 on 2018-10-20 05:36

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leName', models.CharField(max_length=50)),
                ('leIntroduce', models.TextField()),
                ('lePhoto', models.ImageField(blank=True, null=True, upload_to='')),
                ('lePu', models.DateTimeField(blank=True, null=True)),
                ('leMo', models.DateTimeField(blank=True, null=True)),
                ('leMento', models.CharField(max_length=20)),
                ('tag', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
