# Generated by Django 2.0.9 on 2018-10-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_lecture_lesimpleintroduce'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lePlace',
            field=models.TextField(blank=True, null=True),
        ),
    ]
